<a href="https://colab.research.google.com/github/SvanaBirgis/Reiknifraedi/blob/main/Skilaverkefni/S9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Stærðfræði og reiknifræði vor 2022, skiladæmi 9**

Nafn: Svana Björg Birgisdóttir

Samverkamenn: Michael Þór Sverrisson og Hákon Ingi Rafnsson

# **Verkefni 34 (Póker)**

Hér er reitur með (hluta af) lausn á æfingunni í kafla 13.1, sem metur með hermun líkurnar á því að fá tvær tvennur í póker. Fallið pókerhönd er endurbætt miðað við æfinguna til að tryggja að sama spil geti ekki komið fyrir tvisvar. Fræðilegar líkur á tveimur tvennum er 4.75% og ef keyrt er með háu gildi á n fæst hlutfall nálægt því.

```
from random import sample

def pókerhönd():
  stokkur = [(i,j) for i in range(1,5) for j in range(1,14)]
  return sample(stokkur, 5)

def með_tvær_tvennur(hönd):
  # Skilar sönnu ef hönd geymir tvær tvennur
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)                 # búa til mengi
  if len(M) != 3:
    return False                 # það verða að vera 3 gildi
  for spil in M:
    talning = gildi.count(spil)
    if talning > 2: return False # og ekkert spil má koma 3svar
  return True                    # það eru tvær tvennur!

def hlutfall_með_2x2(n):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if með_tvær_tvennur(hönd):
      talning += 1
  return talning/n

hf = hlutfall_með_2x2(100000)
print(f'Hlutfall með tvær tvennur: {hf*100:.1f}%')
```

Í lausninni er spil er táknað með pari `(sort, gildi)` þar sem sortin er á bilinu 1–4 (hjarta, spaði, tígull, lauf) og gildi er á bilinu 1–13 (ás, tvistur,…, kóngur).

Skrifið föll sem kanna hvort hönd geymi:
<ol type="a">
  <li>tvennu</li>
  <li>þrennu</li>
  <li>fullt hús (3 + 2)</li>
  <li>lit (t.d. eintómir spaðar)</li>

</ol>

Hermið slíkar hendur og berið saman við raunverulegar líkur fengnar af netinu.

In [23]:
#a
from random import sample

def pókerhönd():
  stokkur = [(i,j) for i in range(1,5) for j in range(1,14)]
  return sample(stokkur, 5)

def tvenna(hönd):
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)                 # búa til mengi
  if len(M) != 4:
    return False                 # það verða að vera 4 gildi
  for spil in M:
    talning = gildi.count(spil)
    if talning > 2: return False # og ekkert spil má koma 3svar
  return True                    # það eru tvenna

def hlutfall_með_tvennu(n):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if tvenna(hönd):
      talning += 1
  return talning/n

hf = hlutfall_með_tvennu(100000)
print(f'Hlutfall með tvennu: {hf*100:.1f}%')

Hlutfall með tvennu: 42.2%

In [34]:
#b

def þrenna(hönd):
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)                 # búa til mengi
  if len(M) != 3:
    return False                 # það verða að vera 3 gildi
  for spil in M:
    talning = gildi.count(spil)
    if talning > 3: return False # og ekkert spil má koma 4sinnum
  return True                    # það er þrenna

def hlutfall_með_þrennu(n):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if þrenna(hönd):
      talning += 1
  return talning/n

hf = hlutfall_með_þrennu(100000)
print(f'Hlutfall með þrennu: {hf*100:.1f}%')

Hlutfall með þrennu: 6.6%

In [83]:
#c

def fullthús(hönd):
  gildi = [spil[1] for spil in hönd]
  M = set(gildi)                 # búa til mengi
  if len(M) != 2:
    return False                 # það verða að vera 2 gildi
  for spil in M:
    talning = gildi.count(spil)
    if talning > 3: return False # og ekkert spil má koma 4 sinnum
  return True                    # það er fullt hús

def hlutfall_með_fullthús(n):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if fullthús(hönd):
      talning += 1
  return talning/n

hf = hlutfall_með_fullthús(100000)
print(f'Hlutfall með fullthús: {hf*100:.3f}%')

Hlutfall með fullthús: 0.165%

In [124]:
#d

def litur(hönd):
  sort = [spil[0] for spil in hönd]
  gildi = [spil[1] for spil in hönd]
  N = set(sort)
  if len(N) != 1:                # það verður að vera 1 sort
    return False
  M = set(gildi)                 
  if len(M) != 5:
    return False                 # það verða að vera 5 gildi
  for spil in M:
    talning = gildi.count(spil)
    if talning > 1: return False # og ekkert spil má koma 2 sinnum
  return True                    

def hlutfall_með_litur(n):
  talning = 0
  for i in range(n):
    hönd = pókerhönd()
    if litur(hönd):
      talning += 1
  return talning/n

hf = hlutfall_með_litur(100000)
print(f'Hlutfall með litur: {hf*100:.3f}%')

Hlutfall með litur: 0.190%

# *Verkefni 40 (Pandas æfing)**
Í skránni https://cs.hi.is/python/kosningar-2021.txt eru úrslit nýjustu Alþingiskosninga (eftir endurtalningu í NV-kjördæmi), og í skránni https://cs.hi.is/python/flokksnofn.txt eru listabókstafir í fyrsta dálki og þar fyrir aftan eru nöfn flokkanna, sem geta verið tvö eða fleiri orð. Fyrri skrána er auðvelt að lesa með `pd.read_fwf` en þá seinni er líklega auðveldast að lesa með `pd.read_csv` og viðfangi `sep=",\t"` (það eru tab-tákn á eftir kommunum í skránni).

1. Lesið kosningaúrslitin og birtið þau.

2. Lesið seinni skrána, sameinið við fyrri skrána (með `df.join`) og birtið kosningaúrslitin með flokksnöfnum.

3. Bætið við dálki með hlutfalli atkvæða sem hver flokkur fékk og birtið svo nýja töflu yfir þá flokka sem fengu meira en 5% (og komu þar með manni á þing).

In [94]:
#1
import pandas as pd
kosn = pd.read_fwf("https://cs.hi.is/python/kosningar-2021.txt")
display(kosn)

   Listi  Atkvæði  Þingsæti
0      B    34501        13
1      C    16628         5
2      D    48708        16
3      F    17672         6
4      J     8181         0
5      M    10879         3
6      O      836         0
7      P    17233         6
8      S    19825         6
9      V    25114         8
10     Y      144         0

In [95]:
#2

flokk = pd.read_csv("https://cs.hi.is/python/flokksnofn.txt", sep=",\t")

saman = kosn.set_index('Listi').join(flokk.set_index('Listi'))
display(saman)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

       Atkvæði  Þingsæti              Flokkur
Listi
B        34501        13    Framsóknarflokkur
C        16628         5             Viðreisn
D        48708        16   Sjálfstæðisflokkur
F        17672         6     Flokkur fólksins
J         8181         0    Sósíalistaflokkur
M        10879         3           Miðflokkur
O          836         0  Frjálslyndi lýðrfl.
P        17233         6              Píratar
S        19825         6           Samfylking
V        25114         8         Vinstri græn
Y          144         0        Ábyrg framtíð

In [120]:
#3
n = sum(saman["Atkvæði"])
saman["Hlutf"] = saman["Atkvæði"]/n

birt = saman.style.format({"Hlutf": "{:.1%}"})
display(birt)

drop = saman[saman['Hlutf'] >= 0.05]
lok = drop.style.format({"Hlutf": "{:.1%}"})
display(lok)